<?xml version="1.0" encoding="UTF-8"?>

<!--
<!DOCTYPE annuaire[
    <!ELEMENT annuaire (personne)+>
    <!ELEMENT personne (nom,prenom,email+,tel*)>
    <!ATTLIST personne type (etudiant | professeur | administration ) "etudiant">
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT tel (#PCDATA)>
    <!ATTLIST tel type (fixe | portable) #REQUIRED>
]>
-->
<!-- PUBLIC: in intenet -->
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">

<annuaire>
    <personne type="etudiant">
        <nom>ZEGAI</nom>
        <prenom>Houari</prenom>
        <email>houarizegai14@gmail.com</email>
        <email>geekhouari@gmail.com</email>
        <tel type="portable">0797603258</tel>
    </personne>
</annuaire>
