=== jovan0901/academic-projects/Semester3/AdvancedXML/01 - XML & DTD/Ex_06/ex06.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT agenda (personne)* >
<!ELEMENT personne (nom, prenom, adresse, telephone) >
<!ELEMENT adresse (rue, code_postal, ville) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT telephone (#PCDATA) >

<!ELEMENT rue (#PCDATA) >
<!ELEMENT code_postal (#PCDATA) >
<!ELEMENT ville (#PCDATA) >

=== jovan0901/academic-projects/Semester3/AdvancedXML/PW1/Ex_06/ex06.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "ex06.dtd">

<agenda>
    <personne>
        <nom>ZEGAI</nom>
        <prenom>Houari</prenom>
        <adresse>
            <rue>Sidi Khaled</rue>
            <code_postal>14000</code_postal>
            <ville>Tiaret</ville>
        </adresse>
        <telephone>+213797603258</telephone>
    </personne>
</agenda>
