=== jovan0901/academic-projects/Semester3/AdvancedXML/PW2/Ex_05/ex5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="système_solaire">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="étoile" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"></xs:element>
                            <xs:element name="type_spectral" type="xs:string"></xs:element>
                            <xs:element name="âge" type="xs:date"></xs:element>
                            <xs:element name="planète" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="masse">
                                            <xs:complexType xml:base="xs:double">
                                                <xs:attribute name="unit" type="xs:string" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="distance">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minExclusive value="0.4"></xs:minExclusive>
                                                    <xs:maxExclusive value="90"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nom" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="type" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jovan0901/academic-projects/Semester3/AdvancedXML/02 - XSD/Ex_05/ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<système_solaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Houari/Documents/Learn/Master%202/MasterPracticalWork/Semester3/AdvancedXML/PW2/Ex_05/ex5.xsd">
    <étoile>
        <nom>nom0</nom>
        <type_spectral>type_spectral0</type_spectral>
        <âge>2006-05-04</âge>
        <planète type="type0">
            <masse unit="unit0"/>
            <distance>0.41</distance>
            <nom>nom1</nom>
        </planète>
    </étoile>
    <étoile>
        <nom>nom2</nom>
        <type_spectral>type_spectral1</type_spectral>
        <âge>2006-05-04</âge>
        <planète type="type1">
            <masse unit="unit1"/>
            <distance>45.20</distance>
            <nom>nom3</nom>
        </planète>
    </étoile>
</système_solaire>
