=== jovan0901/academic-projects/Semester3/AdvancedXML/01 - XML & DTD/Ex_07/ex07.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT agenda (personne+)>
<!ELEMENT personne (nom, prénom, prenom2?,adresse,téléphone*)>
<!ATTLIST personne
 situation (célibataire|marié|pacsé|concubinage) #REQUIRED
 id_personne ID #REQUIRED
 id_connait IDREFS #IMPLIED>
 
<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom titre (M|Mlle|Mme) #REQUIRED>
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT prénom2 (#PCDATA)>
<!ATTLIST prénom2 prénom3 CDATA #IMPLIED>
<!ELEMENT adresse (rue,code_postal,ville)>
<!ELEMENT téléphone (#PCDATA)>

<!ATTLIST téléphone Type (perso|bureau|portable) #REQUIRED>

<!ELEMENT rue (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>

=== jovan0901/academic-projects/Semester3/AdvancedXML/01 - XML & DTD/Ex_07/ex07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "ex07.dtd">

<agenda>
    <personne situation="célibataire" id_personne="tcl_k22_wjb">
        <nom titre="M">ZEGAI</nom>
        <prénom>Houari</prénom>
        <adresse>
            <rue>Sidi Khaled</rue>
            <code_postal>14000</code_postal>
            <ville>Tiaret</ville>
        </adresse>
    </personne>
</agenda>
